# Assignment-1: Transformations and representations

Team Name: Family 

Roll number: 2019102014 , 2019102017

# Instructions

- Code must be written in Python in Jupyter Notebooks. We highly recommend using anaconda distribution or at the minimum, virtual environments for this assignment. See `Set Up` for detailed step-by-step instructions about the installation setup.
- Save all your results in ```results/<question_number>/<sub_topic_number>/```
- The **References** section provides you with important resources to solve the assignment.
- For this assignment, you will be using Open3D extensively. Refer to [Open3D Documentation](http://www.open3d.org/docs/release/): you can use the in-built methods and **unless explicitly mentioned**, don't need to code from scratch for this assignment. 
- Make sure your code is modular since you may need to reuse parts for future assignments.
- Answer the descriptive questions in your own words with context & clarity. Do not copy answers from online resources or lecture notes.
- The **deadline** for this assignment is on 11/09/2021 at 11:55pm. Please note that there will be no extensions.
- Plagiarism is **strictly prohibited**.


# Submission Instructions

1. Make sure your code runs without any errors after reinitializing the kernel and removing all saved variables.
2. After completing your code and saving your results, zip the folder with name as ``Team_<team_name>_MR2021_Assignment_<assignment_number>.zip``

# Set Up

We highly recommend using anaconda distribution or at the minimum, virtual environments for this assignment. All assignments will be python based, hence familiarising yourself with Python is essential.


## Setting up Anaconda environment (Recommended)

1. Install Anaconda or Miniconda from [here](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html) depending on your requirements.
2. Now simply run `conda env create -f environment.yml` in the current folder to create an environment `mr_assignment1` (`environment.yml` can be found in `misc/`).
3. Activate it using `conda activate mr_assignment1`.

## Setting up Virtual environment using venv

You can also set up a virtual environment using venv

1. Run `sudo apt-get install python3-venv` from command line.
2. `python3 -m venv ~/virtual_env/mr_assignment1`. (you can set the environment path to anything)
3. `source ~/virtual_env/mr_assignment1/bin/activate`
4. `pip3 install -r requirements.txt` from the current folder (`requirements.txt` can be found in `misc/`).

# <b> Checklist
1. 
* 1 Done
* 2 Done
* 3 Done
* 4 Done
* 5 Done
    
    
2. <br>
a. <br>
* 1 Done
* 2 Done
* 3 Done
* 4 Done
    
b. <br>
* 1 Done
* 2 Done
* 3 Done
* 4 Done
    
c. <br>
* 1 Done
* 2 Done
* 3 Done
    
    
3. <br>
a. <br>
* 1 Done
* 2 Done
* 3 Done
    
b. <br>
* 1 Done
* 2 
* 3 
* 4
    


In [37]:
import open3d as o3d
import numpy as np
import math
import copy
import pytorch3d.transforms as pt

# 1. Getting started with Open3D

Open3D is an open-source library that deals with 3D data, such as point clouds, mesh. We'll be using Open3D frequently as we work with point clouds. Let's start with something simple:

<img src="misc/bunny.jpg" alt="drawing" width="200"/>

1. Read the Stanford Bunny file (in `data/`) given to you and visualise it using Open3D.
2. Convert the mesh to a point cloud and change the colour of points.
3. Set a predefined viewing angle (using Open3D) for visualization and display the axes while plotting.
4. Scale, Transform, and Rotate the rabbit (visualise after each step).
5. Save the point cloud as bunny.pcd.

In [2]:
# Load the mesh file
bunny = o3d.io.read_triangle_mesh("data/bunny.ply")
print(bunny)    

TriangleMesh with 35947 points and 69451 triangles.


In [3]:
# Visualisation
o3d.visualization.draw_geometries([bunny])  

In [4]:
# Convert from mesh to point cloud
bunny = o3d.io.read_point_cloud("data/bunny.ply")
o3d.io.write_point_cloud("bunnyPointCloud.pcd", bunny)

True

In [5]:
# Paint point cloud
bunny.paint_uniform_color([1,0.8,0.4])
mesh_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.025, origin=[0, 0, 0])
o3d.visualization.draw_geometries([bunny,mesh_frame])

In [6]:
# Set predefined viewing angle 
    # Press ctrl+c to fix viewing angle, whenever you change type ctrl+v to go bac to initial position
o3d.visualization.draw_geometries([bunny,mesh_frame],
            front = [ 0.48458812719692307, 0.62044224539450676, 0.61662449441260558 ],
            lookat = [ -0.016840399999999998, 0.092910499999999993, -0.0015369499999999987 ],
            up = [ 0.50141338827227588, 0.38059744472519991, -0.77700077164052073 ],
            zoom = 0.69999999999999996)

In [7]:
#Scaling
ScaledBunny = copy.deepcopy(bunny).scale(0.1,[0,0,0])
o3d.visualization.draw_geometries([ScaledBunny,mesh_frame])

In [8]:
#Transform
T = np.eye(4)
R = bunny.get_rotation_matrix_from_xyz((-0.7 * np.pi, 0, -0.6 * np.pi))
t = np.array([0.1,0.2,0])
T[:3,:3] = R
T[:3,3] = t
TransformedBunny = copy.deepcopy(bunny).transform(T)
o3d.visualization.draw_geometries([TransformedBunny,mesh_frame])

In [9]:
# Rotation
R = bunny.get_rotation_matrix_from_xyz((-0.7 * np.pi, 0, -0.6 * np.pi))
RotatedBunny = copy.deepcopy(bunny).rotate(R,center=(0,0,0))
o3d.visualization.draw_geometries([RotatedBunny,mesh_frame])

# 2. Transformations and representations

## a) Euler angles
1. Write a function that returns a rotation matrix given the angles $\alpha$, $\beta$, and $\gamma$ in radians (X-Y-Z)

2. Solve for angles using ```fsolve from scipy``` for three initializations of your choice and compare.
$$M(\alpha , \beta ,\gamma)=\left[\begin{array}{rrr}0.26200263 & -0.19674724 & 0.944799 \\0.21984631 & 0.96542533 & 0.14007684 \\
    -0.93969262 & 0.17101007 & 0.29619813\end{array}\right] 
$$

$$N(\alpha , \beta ,\gamma)=\left[\begin{array}{rrr}0 & -0.173648178 &  0.984807753 \\0 & 0.984807753 & 0.173648178 \\
    -1 & 0 & 0\end{array}\right] 
$$

3. What is a Gimbal lock? 

4. Show an example where a Gimbal lock occurs and visualize the Gimbal lock on the given bunny point cloud. You have to show the above by **animation** (cube rotating along each axis one by one).
    - *Hint: Use Open3D's non-blocking visualization and discretize the rotation to simulate the animation. For example, if you want to rotate by $30^{\circ}$ around a particular axis, do in increments of $5^{\circ}$ 6 times to make it look like an animation.*


### Answers
3. Gimbal lock is when there is 1-DOF loss in a 3D mechanism  due to 2 out of 3 axes driven into parallel configuration. Due to the parallel configuration, there isnt any rotation along about one of the axis

In [10]:
def XYZtoRotationMatrix(a,b,g):
    cosA = math.cos(a)
    cosB = math.cos(b)
    cosG = math.cos(g)
    sinA = math.sin(a)
    sinB = math.sin(b)
    sinG = math.sin(g)
    
    
#     rotationMatrix = [[cBcG , ((sinA * sBcG) + cAsG), ((-cosA * sBcG) + sAsG)],
#                       [-cBsG  , ((-sinA * sBsG) + cAcG), ((cosA * sBsG) + sAcG)],
#                       [sinB , -sAcB , cAcB]]
    rotationMatrix = [[cosB * cosG, -cosB * sinG, sinB],
                      [((sinA * sinB * cosG) + (cosA * sinG)) , ((-sinA * sinB * sinG) + (cosA*cosG)), (-sinA*cosB)],
                      [((-cosA * sinB * cosG) + sinA * sinG) ,((cosA * sinB * sinG) + (sinA*cosG) ) , (cosA * cosB) ]]
    return rotationMatrix

In [11]:
from scipy.optimize import fsolve

M = np.array([[0.26200263,-0.19674724,0.944799],[0.21984631,0.96542533,0.14007684],[-0.93969262,0.17101007,0.29619813]])
N = np.array([[0,-0.173648178,0.984807753],[0,0.984807753,0.173648178],[-1,0,0]])

#initialize 3 points
a = (1,0,0)
b = (0,1,0)
c = (0,0,1)

ahat = np.dot(M,np.array(a))
bhat = np.dot(M,np.array(b))
chat = np.dot(M,np.array(c))

def EulerOptimize(angles):
    R = XYZtoRotationMatrix(*angles)
    acap = np.dot(np.array(R),a)
    bcap = np.dot(np.array(R),b)
    ccap = np.dot(np.array(R),c)
    
    return [np.linalg.norm(acap-ahat),np.linalg.norm(bcap-bhat),np.linalg.norm(ccap-chat)]
M_euler = fsolve(EulerOptimize,[math.pi/3,math.pi/4,0.1])
# x0 = (0,0,0) #initialization
# R0 = XYZtoRotationMatrix(*x0)
# np.array(R0)
# R0 = np.reshape(R0,(9,))
# M = np.array([[0.26200263,-0.19674724,0.944799],[0.21984631,0.96542533,-0.93969262],[0.14007684,0.17101007,0.29619813]])
# M= np.reshape(M,(9,))
# def EulerOptimize(R):
#     return M-R

/home/wandra/Documents/SEM-5/DIP/DIP/lib/python3.6/site-packages/scipy/optimize/minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)


In [12]:
#initialize 3 points
ahat = np.dot(N,np.array(a))
bhat = np.dot(N,np.array(b))
chat = np.dot(N,np.array(c))

def EulerOptimize(angles):
    R = XYZtoRotationMatrix(*angles)
    acap = np.dot(np.array(R),a)
    bcap = np.dot(np.array(R),b)
    ccap = np.dot(np.array(R),c)
    return [np.linalg.norm(acap-ahat),np.linalg.norm(bcap-bhat),np.linalg.norm(ccap-chat)]

N_euler = fsolve(EulerOptimize,[math.pi/3,math.pi/4,0.1])

In [27]:
print(M_euler)
print(N_euler)

[-0.44174663  1.23698059  0.64409996]
[ 1.57079633  1.74532925 -1.57079633]


In [13]:
#testing purposes

#R = M
# sy = math.sqrt(R[0,0] * R[0,0] +  R[1,0] * R[1,0])
# singular = sy < 1e-6
# if  not singular :
#     x = math.atan2(R[2,1] , R[2,2])
#     y = math.atan2(-R[2,0], sy)
#     z = math.atan2(R[1,0], R[0,0])
# else :
#     x = math.atan2(-R[1,2], R[1,1])
#     y = math.atan2(-R[2,0], sy)
#     z = 0
# [x,y,z]
#
def euler_to_rotMat(roll, pitch, yaw):
    Rz_yaw = np.array([
        [np.cos(yaw), -np.sin(yaw), 0],
        [np.sin(yaw),  np.cos(yaw), 0],
        [          0,            0, 1]])
    Ry_pitch = np.array([
        [ np.cos(pitch), 0, np.sin(pitch)],
        [             0, 1,             0],
        [-np.sin(pitch), 0, np.cos(pitch)]])
    Rx_roll = np.array([
        [1,            0,             0],
        [0, np.cos(roll), -np.sin(roll)],
        [0, np.sin(roll),  np.cos(roll)]])
    # R = RzRyRx
    rotMat = np.dot(Rx_roll, np.dot(Ry_pitch, Rz_yaw)).round(8)
    return rotMat

# roll = 1.57079633
# pitch = 1.74532925
# yaw = -1.57079633
rotM = euler_to_rotMat(M_euler[0],M_euler[1],M_euler[2])
rotN = euler_to_rotMat(N_euler[0],N_euler[1],N_euler[2])

print(rotM)
print(rotN)

[[ 0.26200263 -0.19674724  0.944799  ]
 [ 0.21984631  0.96542534  0.14007684]
 [-0.93969262  0.17101007  0.29619813]]
[[-0.         -0.17364818  0.98480775]
 [ 0.          0.98480775  0.17364818]
 [-1.          0.          0.        ]]


In [14]:
#animation code


bunny1 = o3d.io.read_triangle_mesh("data/bunny.ply")
bunny2 = o3d.io.read_triangle_mesh("data/bunny.ply")

mesh_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.025, origin=[0, 0, 0])

vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(bunny1)
vis.add_geometry(bunny2)
vis.add_geometry(mesh_frame)

#rotate bunny by alpha degrees around y axis
alpha = math.pi/10
beta = math.pi/2
gamma = 9*math.pi/10


icp_iteration = 240 #increase this number for slower animation

#rotate about x 30 degrees for bunny1 and 60 degrees for bunny2
R1 = XYZtoRotationMatrix(alpha/icp_iteration,0,0)
R2 = XYZtoRotationMatrix(gamma/icp_iteration,0,0)

for i in range(icp_iteration):
    bunny1.rotate(R1,center=(0,0,0))
    bunny2.rotate(R2,center=(0,0,0))
    vis.update_geometry(bunny1)
    vis.update_geometry(bunny2)
    vis.poll_events()
    vis.update_renderer()
    
#rotate about y 90 degrees for both bunny1 and bunny2
R1 = XYZtoRotationMatrix(0,beta/icp_iteration,0)
R2 = XYZtoRotationMatrix(0,beta/icp_iteration,0)
for i in range(icp_iteration):
    bunny1.rotate(R1,center=(0,0,0))
    bunny2.rotate(R2,center=(0,0,0))
    vis.update_geometry(bunny1)
    vis.update_geometry(bunny2)
    vis.poll_events()
    vis.update_renderer()

    
#rotate about z 60 degrees for bunny1 and 30 degrees for bunny2
R1 = XYZtoRotationMatrix(0,0,gamma/icp_iteration)
R2 = XYZtoRotationMatrix(0,0,alpha/icp_iteration)
for i in range(icp_iteration):
    bunny1.rotate(R1,center=(0,0,0))
    bunny2.rotate(R2,center=(0,0,0))
    vis.update_geometry(bunny1)
    vis.update_geometry(bunny2)
    vis.poll_events()
    vis.update_renderer()
vis.destroy_window()

## b) Quaternions

1. What makes Quaternions popular in graphics? 
2. Convert a rotation matrix to quaternion and vice versa. Do not use inbuilt libraries for this question.
3. Perform matrix multiplication of two $\mathcal{R}_{3 \times 3}$ rotation matrices and perform the same transformation in the quaternion space. Verify if the final transformation obtained in both the cases are the same.
4. Try to interpolate any 3D model (cube / bunny / not sphere obviously!!) between two rotation matrices and visualize!

The above questions require you to **code your own functions** and **only verify** using inbuilt functions.

### Answers
1. Interpolation is easily possible in quternions which is desirable in graphics. All transformations are orthonormal. It can also help in rotation about multiple axis at a time instead of doing composite matrix rotations which could lead to gimbal lock

In [34]:
def QtoR(q0,q1,q2,q3):
    # q = q0 + q1i + q2j + q3k
    a11 = (2 * q0 * q0) + (2 * q1 * q1) - 1
    a12 = (2 * q1 * q2) - (2 * q0 * q3)
    a13 = (2 * q1 * q3) + (2 * q0 * q2)
    
    a21 = (2 * q1 * q2) + (2 * q0 * q3)
    a22 = (2 * q0 * q0) - (2 * q2 * q2) - 1
    a23 = (2 * q2 * q3) - (2 * q0 * q1)
    
    a31 = (2 * q1 * q3) - (2 * q0 * q2)
    a32 = (2 * q2 * q3) + (2 * q0 * q1)
    a33 = (2 * q0 * q0) - (2 * q3 * q3) - 1
    Rmatrix = [[a11, a12, a13],
               [a21, a22, a23],
               [a31, a32, a33]]
    return Rmatrix

In [35]:
print(QtoR(0,1,0,0))

[[1, 0, 0], [0, -1, 0], [0, 0, -1]]


In [17]:
def RtoQ(R):
    traceR = R[0][0] + R[1][1] + R[2][2]
    absq0 = math.sqrt((traceR + 1)/4)
    absq1 = math.sqrt((R[0][0] - R[1][1] - R[2][2] + 1)/4)
    absq2 = math.sqrt((-R[0][0] + R[1][1] - R[2][2] + 1)/4)
    absq3 = math.sqrt((-R[0][0] - R[1][1] + R[2][2] + 1)/4)
    maxQ = max(absq0,absq1,absq2,absq3)
    if maxQ == absq0:
        q0 = absq0
        q1 = (R[2][1] - R[1][2])/(4 * q0)
        q2 = (R[0][2] - R[2][0])/(4 * q0)
        q3 = (R[1][0] - R[0][1])/(4 * q0)
    elif maxQ == absq1:
        q1 = absq1
        q0 = (R[2][1] - R[1][2])/(4 * q1)
        q2 = (R[0][1] + R[1][0])/(4 * q1)
        q3 = (R[0][2] + R[2][0])/(4 * q1)
    elif maxQ == absq2:
        q2 = absq2
        q0 = (R[0][2] - R[2][0])/(4 * q2)
        q1 = (R[0][1] + R[1][0])/(4 * q2)
        q3 = (R[1][2] + R[2][1])/(4 * q2)
    else:
        q3 = absq3
        q0 = (R[1][0] - R[0][1])/(4 * q3)
        q1 = (R[0][2] + R[2][0])/(4 * q3)
        q2 = (R[1][2] + R[2][1])/(4 * q3)
     
    q = [q0,q1,q2,q3]
    return q

In [41]:
R = [[0, -1, 0], 
     [1, 0, 0], 
     [0, 0, 1]]
print(RtoQ(R))

[0.7071067811865476, 0.0, 0.0, 0.7071067811865475]


In [19]:
Rx270 = [[1, 0, 0], 
         [0, 0, 1], 
         [0, -1, 0]]
nRx180 = [[1, 0, 0], 
         [0, -1, 0], 
         [0, 0, -1]]
nRx90 = [[1, 0, 0], 
         [0, 0, 1], 
         [0, -1, 0]]
q1 = RtoQ(Rx270)
q2 = RtoQ(nRx180)
q3 = RtoQ(nRx90)
q1q2 = [0,0,0,0]
q1q2[0] = q1[0]*q2[0] - q1[1]*q2[1] - q1[2]*q2[2] - q1[3]*q2[3]
q1q2[1] = q1[0]*q2[1] + q1[1]*q2[0] + q1[2]*q2[3] - q1[3]*q2[2]
q1q2[2] = q1[0]*q2[2] - q1[1]*q2[3] + q1[2]*q2[0] + q1[3]*q2[1]
q1q2[3] = q1[0]*q2[3] + q1[1]*q2[2] - q1[2]*q2[1] + q1[3]*q2[0]
qMult = [0,0,0,0]
qMult[0] = q1q2[0]*q3[0] - q1q2[1]*q3[1] - q1q2[2]*q3[2] - q1q2[3]*q3[3]
qMult[1] = q1q2[0]*q3[1] + q1q2[1]*q3[0] + q1q2[2]*q3[3] - q1q2[3]*q3[2]
qMult[2] = q1q2[0]*q3[2] - q1q2[1]*q3[3] + q1q2[2]*q3[0] + q1q2[3]*q3[1]
qMult[3] = q1q2[0]*q3[3] + q1q2[1]*q3[2] - q1q2[2]*q3[1] + q1q2[3]*q3[0]
qMult = np.array(qMult).round(10)

Rmult = [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]
Rmult = np.dot(np.dot(Rx270, nRx180),nRx90)
print(qMult)
print(Rmult)

[1. 0. 0. 0.]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [20]:
print(q1)
print(q2)
print(q3)

[0.7071067811865476, -0.7071067811865475, 0.0, 0.0]
[0.0, 1.0, 0.0, 0.0]
[0.7071067811865476, -0.7071067811865475, 0.0, 0.0]


In [33]:
# qR1 = np.array(QtoR(q1[0],q1[1],q1[2],q1[3])).round(10)
# qR2 = np.array(QtoR(q2[0],q2[1],q2[2],q2[3])).round(10)
# qR3 = np.array(QtoR(q3[0],q3[1],q3[2],q3[3])).round(10)
# # print(QtoR(q1[0],q1[1],q1[2],q1[3]))
# # print(QtoR(q2[0],q2[1],q2[2],q2[3]))
# # print(QtoR(q3[0],q3[1],q3[2],q3[3]))
# print(qR1)
# print(qR2)
# print(qR3)


In [22]:
print(RtoQ(Rmult))

[1.0, 0.0, 0.0, 0.0]


In [23]:
#linear interpolation (or lerp)

#first box
mesh_box_a = o3d.geometry.TriangleMesh.create_box(width=1.0,
                                                height=1.0,
                                                depth=1.0)
mesh_box_a.paint_uniform_color([0.9, 0.1, 0.1])

#rotation matrix for a
Ra = XYZtoRotationMatrix(0,0,0)

#second box that we rotate by 90 degrees around y axis
mesh_box_b = o3d.geometry.TriangleMesh.create_box(width=1.0,
                                                height=1.0,
                                                depth=1.0)
mesh_box_b.paint_uniform_color([0.1, 0.1, 0.7])

#rotation matrix for b
Rb = XYZtoRotationMatrix(0,0,math.pi/4)

mesh_box_b.rotate(Rb,center = (0,0,0))

#interpolated box
mesh_box_c = o3d.geometry.TriangleMesh.create_box(width=1.0,
                                                height=1.0,
                                                depth=1.0)
mesh_box_c.paint_uniform_color([0.1, 0.9, 0.1])

#getting quaternions and doing linear interpolation (lerp)
qa = RtoQ(Ra)
qb = RtoQ(Rb)

interp_value = 0.5
qc = np.array(qa) + interp_value*(np.array(qb)-np.array(qa))
Rc = QtoR(*qc)
mesh_box_c.rotate(Rc,center = (0,0,0))


#red is original, blue is rotated by pi/4 and green is interpolated
o3d.visualization.draw_geometries([mesh_box_a,mesh_box_b,mesh_box_c])

In [24]:
#spherical interpolation (or slerp)

#first box
mesh_box_a = o3d.geometry.TriangleMesh.create_box(width=1.0,
                                                height=1.0,
                                                depth=1.0)
mesh_box_a.paint_uniform_color([0.9, 0.1, 0.1])

#rotation matrix for a
Ra = XYZtoRotationMatrix(0,0,0)

#second box that we rotate by 90 degrees around y axis
mesh_box_b = o3d.geometry.TriangleMesh.create_box(width=1.0,
                                                height=1.0,
                                                depth=1.0)
mesh_box_b.paint_uniform_color([0.1, 0.1, 0.7])

#rotation matrix for b
Rb = XYZtoRotationMatrix(0,0,math.pi/4)

mesh_box_b.rotate(Rb,center = (0,0,0))

#interpolated box
mesh_box_c = o3d.geometry.TriangleMesh.create_box(width=1.0,
                                                height=1.0,
                                                depth=1.0)
mesh_box_c.paint_uniform_color([0.1, 0.9, 0.1])

#getting quaternions and doing linear interpolation (lerp)
qa = RtoQ(Ra)
qb = RtoQ(Rb)

interp_value = 0.5
qa = np.array(qa)
qb = np.array(qb)
qa = qa/np.linalg.norm(qa)
qb = qb/np.linalg.norm(qb)

angle = math.acos(np.sum(np.multiply(qa,qb)))
qc = 0
if angle==0:
    qc = qa
else:
    qc = (math.sin((1-interp_value)*angle)*qa + math.sin(interp_value*angle)*qb)/math.sin(angle)
qc = qc/np.linalg.norm(qc)
Rc = QtoR(*qc)
mesh_box_c.rotate(Rc,center = (0,0,0))


#red is original, blue is rotated by pi/4 and green is interpolated
o3d.visualization.draw_geometries([mesh_box_a,mesh_box_b,mesh_box_c])

## c) Exponential maps (Bonus)

1. What is the idea behind exponential map representation of rotation matrices?
2. Perform matrix exponentiation and obtain the rotation matrix to rotate a vector $P$ around $\omega$ for $\theta$ seconds.
$$
\omega = \begin{bmatrix}2 \\ 1 \\ 15 \end{bmatrix}
$$

$$
\theta = 4.1364
$$

3. Compute the logarithmic map (SO(3) to so(3)) of the rotation matrix to obtain the rotation vector and the angle of rotation
$$
\begin{bmatrix}
0.1 &  -0.9487 & 0.3 \\
0.9487 & 0.  & -0.3162 \\
0.3   &  0.3162  & 0.9 
\end{bmatrix}
$$
You can use inbuilt libraries **only to verify** your results.

### Answers
1. It can be seen that rotation matrix R $\in$ SO(3), can be expressed as R = $e^{[\hat{w}]\theta}$ . Here, $e^{[\hat{w}]\theta}$ is the exponential coordinate for SO(3). Depticted by a single rotation around one axis which is represented by a 3-D unit vector and scalar angle. So the process of transformation from axis-angle(omega-theta) $\in$ so(3) to R(rotational matrix) is known as exponential map. 
<center>exp: so(3) $\rightarrow$ SO(3) </center>

Idea is to use a taylor series expansion to derive a closed-form relation between both the representations.

In [79]:
# Part 2 
def exponentialMap(Omega,Theta):
    I = [[1,0,0],
         [0,1,0],
         [0,0,1]]
    I = np.array(I)
    x = Omega[0]
    y = Omega[1]
    z = Omega[2]
    Axis = [[0,-z,y],
            [z,0,-x],
            [-y,x,0]]
    Axis = np.array(Axis)
    
    AxisSq = np.matmul(Axis, Axis)
    
    Axis = math.sin(Theta) * Axis
    AxisSq = (1-math.cos(Theta)) * AxisSq
    
    R = I + Axis + AxisSq
    
    
    
    return R.round(3)


In [62]:
Omega = [2,1,15]
Omega[0] = Omega[0]/math.sqrt((Omega[0]*Omega[0]) + (Omega[1]*Omega[1]) + (Omega[2]*Omega[2]))
Omega[1] = Omega[1]/math.sqrt((Omega[0]*Omega[0]) + (Omega[1]*Omega[1]) + (Omega[2]*Omega[2]))
Omega[2] = Omega[2]/math.sqrt((Omega[0]*Omega[0]) + (Omega[1]*Omega[1]) + (Omega[2]*Omega[2]))
print(Omega)

[0.1318760946791574, 0.0665164512636101, 0.9999515240970164]


In [66]:
Theta = 4.1364 #in seconds
Theta = Theta / 3600 #in degrees
print(Theta)
Theta = Theta * (math.pi/180)
print(Theta) # in radians 0.000026005405855 rad

0.001149
2.0053833105414847e-05


In [81]:
print(exponentialMap(Omega,Theta))

[[ 1. -0.  0.]
 [ 0.  1. -0.]
 [-0.  0.  1.]]


In [55]:
# Part 3
def LogarithmicMap(R):
    traceR = R[0][0] + R[1][1] + R[2][2]
    cosTheta = (traceR - 1)/2
    sinTheta = math.sqrt((3-traceR) * (1+traceR))/2
    Theta = math.asin(sinTheta)
    if sinTheta < 0:
        Theta = -Theta
            
    R = np.array(R) 
    R_T = np.transpose(R)
          
    
    if Theta == 0:
        print("AnyAxis")
        Omega = [0,0,0]
    elif sinTheta == 0:
            Omega = np.array([math.sqrt((R[0][0]+1)/2) , math.sqrt((R[1][1]+1)/2), math.sqrt((R[2][2]+1)/2)])
            Theta = math.pi
            print("180 degrees")
    else:
        C2 = 1/(2*sinTheta)
        w = np.array([R[2][1] - R[1][2], R[0][2] - R[2][0], R[1][0] - R[0][1]])
        Omega = C2 * w
        
    return Theta, Omega;

In [54]:
RR = [[0.1, -0.9487, 0.3], 
     [0.9487, 0, -0.3162], 
     [0.3, 0.3162, 0.9]]
print(LogarithmicMap(RR))

(1.5707963267948966, array([0.3162, 0.    , 0.9487]))


# 3. Data representations

## a) Octomaps

1. Why is an Octomap memory efficient?
2. When do we update an Octomap and why?
3. When would you likely use an octomap instead of a point cloud?
 

1. Mappings are needed to be efficient as mpas are an integral part of automation systems for planning and navigation. Therefore,  these octomaps are required to memory-efficient to map large environments. 
2. We can add new information from sensors at any point of time as the updation is done is a probablistic manner. The updates are only done on the leaf nodes.
3. Octomaps are preferred over point clouds when we are dealing with large and dynamic regions as they are able to probablistically update multiple measurments as they are computed. Secondly, point clouds aren't memory efficient as they store large amount of points. Thirdly, octomaps are preferred when we are dealing with regions with obstaclees as they can differenciate between regions that are unmapped and regions aren don't have any obstacles.


## b) Signed Distance Functions

1. How do we determine object surfaces using SDF?
2. How do we aggregate views from multiple cameras? (just a general overview is fine)
3. Which preserves details better? Voxels or SDF? Why?
4. What’s an advantage of SDF over a point cloud?


1. SDF(signed distance fields) are used to describe volume of an object. In a metric space, it is used to identift the distance of a given point from its boundary. They are marked by positive values inside the object and progressively decreases when moving towards the boundary and finally reaches zero, So when the SDF value is zero(zero-crossing while interpolation), we can conclude that it refers to the object surface.
<br>
2. To aggregate and update views, we fuse the infomation similar to probablity based approach. We do a weighted average where we have distance computed from a particular voxel to surface as seen from that particular camera view. This process is done for each and every voxel present in the scene.

3. SDF is better due to the following reasons: 
    a. Noise gets averaged out with multiple measurements thus giving better details
    b. We can get a sub voxel accuracy using least squares estimate
<br>
4. SDF is preferred over point cloud as it is more useful in planning as essentially store distances from surface. It is time and storage efficient as truncation saves space(values outside support of weigt functin wont be stored).

# References and Resources

1. Gimbal locks and quaternions: https://youtu.be/YF5ZUlKxSgE
2. Exponential map: 
    1. 3 Blue 1 Brown: https://youtu.be/O85OWBJ2ayo
    2. Northwestern Robotics: https://youtu.be/v_KBHaG0mas
3. Bunny ply is taken from: http://graphics.im.ntu.edu.tw/~robin/courses/cg03/model/